package tr.gov.kocaeli.sehir.inspection.application;
import org.locationtech.jts.io.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tr.gov.kocaeli.sehir.audit.application.AuditService;import tr.gov.kocaeli.sehir.common.api.ApiException;import tr.gov.kocaeli.sehir.common.security.*;import tr.gov.kocaeli.sehir.request.application.RequestService;import tr.gov.kocaeli.sehir.request.api.RequestDtos;import tr.gov.kocaeli.sehir.request.domain.RequestStatus;import java.math.BigDecimal;import java.sql.Types;import java.time.*;import java.util.*;
@Service public class InspectionService{
 private final JdbcClient jdbc;private final CurrentUserService current;private final RequestService requests;private final AuditService audit;private final int minimumPhotos;
 public InspectionService(JdbcClient jdbc,CurrentUserService current,RequestService requests,AuditService audit,@Value("${app.inspection.minimum-photo-count}")int minimumPhotos){this.jdbc=jdbc;this.current=current;this.requests=requests;this.audit=audit;this.minimumPhotos=minimumPhotos;}
 @Transactional public Map<String,Object>create(UUID requestId,Create c){requests.get(requestId);UUID id=UUID.randomUUID();OffsetDateTime plannedAt=c.plannedAt()==null?null:OffsetDateTime.ofInstant(c.plannedAt(),ZoneOffset.UTC);jdbc.sql("insert into inspection(id,request_id,responsible_user_id,team_name,planned_at,status,geometry) values(:id,:r,:u,:t,:p,'PLANNED',ST_GeomFromText(:g,4326))").param("id",id).param("r",requestId).param("u",c.responsibleUserId()).param("t",c.teamName()).param("p",plannedAt,Types.TIMESTAMP_WITH_TIMEZONE).param("g",c.geometryWkt()).update();audit.record("CREATE","INSPECTION",id,null,c);return get(id);}
 @Transactional public Map<String,Object>complete(UUID id,Complete c){if(c.technicalDescription()==null||c.technicalDescription().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"TECHNICAL_DESCRIPTION_REQUIRED","Teknik açıklama zorunludur");if(c.result()==null||c.result().isBlank())throw new ApiException(HttpStatus.BAD_REQUEST,"INSPECTION_RESULT_REQUIRED","Keşif sonucu zorunludur");if(c.photoCount()<minimumPhotos)throw new ApiException(HttpStatus.BAD_REQUEST,"MINIMUM_PHOTO_COUNT","En az "+minimumPhotos+" fotoğraf gereklidir");var old=get(id);jdbc.sql("update inspection set technical_description=:d,measurements=:m,estimated_cost=:c,result=:r,photo_count=:p,status='COMPLETED',occurred_at=now(),updated_at=now(),version=version+1 where id=:id").param("d",c.technicalDescription()).param("m",c.measurements()).param("c",c.estimatedCost()).param("r",c.result()).param("p",c.photoCount()).param("id",id).update();UUID requestId=(UUID)old.get("requestId");var request=requests.get(requestId);if(request.status()==RequestStatus.ASSIGNED)requests.transition(requestId,new RequestDtos.Transition(RequestStatus.FIELD_REVIEW,"Keşif başlatıldı"));requests.transition(requestId,new RequestDtos.Transition(RequestStatus.DECISION_PENDING,"Keşif tamamlandı"));var after=get(id);audit.record("STATUS_CHANGE","INSPECTION",id,old,after);return after;}
 public Map<String,Object>get(UUID id){var result=jdbc.sql("select id,request_id,responsible_user_id,team_name,planned_at,occurred_at,technical_description,measurements,estimated_cost,result,photo_count,status,version from inspection where id=:id").param("id",id).query((rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getObject("id",UUID.class));m.put("requestId",rs.getObject("request_id",UUID.class));m.put("responsibleUserId",rs.getObject("responsible_user_id",UUID.class));m.put("teamName",rs.getString("team_name"));m.put("plannedAt",rs.getObject("planned_at"));m.put("occurredAt",rs.getObject("occurred_at"));m.put("technicalDescription",rs.getString("technical_description"));m.put("measurements",rs.getString("measurements"));m.put("estimatedCost",rs.getBigDecimal("estimated_cost"));m.put("result",rs.getString("result"));m.put("photoCount",rs.getInt("photo_count"));m.put("status",rs.getString("status"));m.put("version",rs.getLong("version"));return m;}).optional().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"INSPECTION_NOT_FOUND","Keşif bulunamadı"));requests.get((UUID)result.get("requestId"));return result;}
 public record Create(UUID responsibleUserId,String teamName,Instant plannedAt,String geometryWkt){}public record Complete(String technicalDescription,String measurements,BigDecimal estimatedCost,String result,int photoCount){}
}
