package tr.gov.kocaeli.sehir.request.application;
import org.locationtech.jts.io.*;import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tr.gov.kocaeli.sehir.audit.application.AuditService;import tr.gov.kocaeli.sehir.common.api.ApiException;import tr.gov.kocaeli.sehir.common.security.*;import tr.gov.kocaeli.sehir.organization.application.UnitScopeService;import tr.gov.kocaeli.sehir.request.api.RequestDtos.*;import tr.gov.kocaeli.sehir.request.domain.*;import tr.gov.kocaeli.sehir.request.infrastructure.*;import java.time.*;import java.util.*;
@Service public class RequestService{
 private final CityRequestRepository requests;private final RequestTransitionRepository transitions;private final UnitScopeService scope;private final CurrentUserService current;private final JdbcTemplate jdbc;private final AuditService audit;private final WKTReader reader=new WKTReader();private final WKTWriter writer=new WKTWriter();
 public RequestService(CityRequestRepository requests,RequestTransitionRepository transitions,UnitScopeService scope,CurrentUserService current,JdbcTemplate jdbc,AuditService audit){this.requests=requests;this.transitions=transitions;this.scope=scope;this.current=current;this.jdbc=jdbc;this.audit=audit;}
 @Transactional public View create(Create c){scope.require(c.responsibleUnitId());try{var geometry=reader.read(c.geometryWkt());if(!Set.of("Point","LineString","Polygon").contains(geometry.getGeometryType()))throw new ApiException(HttpStatus.BAD_REQUEST,"GEOMETRY_TYPE","Yalnızca Point, LineString veya Polygon kabul edilir");geometry.setSRID(4326);String no=jdbc.queryForObject("select 'TLP-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('request_no_seq')::text,6,'0')",String.class);var actor=current.require();var entity=CityRequest.create(no,c.title(),c.description(),c.requestType(),c.channel(),c.priority(),c.applicantName(),c.applicantContact(),c.responsibleUnitId(),c.districtId(),c.neighborhoodId(),c.address(),geometry,c.externalReference(),actor.id());requests.save(entity);transitions.save(new RequestTransition(entity.getId(),null,RequestStatus.NEW,"Talep oluşturuldu",actor.id()));var view=toView(entity);audit.record("CREATE","REQUEST",entity.getId(),null,view);return view;}catch(ParseException e){throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_GEOMETRY","Geometri WKT biçiminde geçersiz");}}
 @Transactional(readOnly=true)public PageView<View> list(RequestStatus status,String q,Pageable pageable){var page=requests.search(scope.allowedUnits(),status,q==null||q.isBlank()?null:q,pageable).map(this::toView);return new PageView<>(page.getContent(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages());}
 @Transactional(readOnly=true)public View get(UUID id){return toView(require(id));}
 @Transactional(readOnly=true)public List<View> duplicates(UUID id){require(id);return requests.duplicates(id,scope.allowedUnits()).stream().map(this::toView).toList();}
 @Transactional public View assign(UUID id,Assign c){var r=require(id);scope.require(c.unitId());var before=toView(r);r.assign(c.unitId(),c.assigneeId(),current.require().id());requests.save(r);var after=toView(r);audit.record("ASSIGNMENT_CHANGE","REQUEST",id,before,after);return after;}
 @Transactional public View transition(UUID id,Transition c){var r=require(id);var before=toView(r);try{var from=r.transition(c.status(),current.require().id());transitions.save(new RequestTransition(id,from,c.status(),c.note(),current.require().id()));var after=toView(r);audit.record("STATUS_CHANGE","REQUEST",id,before,after);return after;}catch(IllegalStateException e){throw new ApiException(HttpStatus.CONFLICT,"INVALID_STATUS_TRANSITION",e.getMessage());}}
 @Transactional public void archive(UUID id){var r=require(id);r.archive();audit.record("SOFT_DELETE","REQUEST",id,toView(r),null);}
 private CityRequest require(UUID id){return requests.findScoped(id,scope.allowedUnits()).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"REQUEST_NOT_FOUND","Talep bulunamadı"));}
 private View toView(CityRequest r){return new View(r.getId(),r.getRequestNo(),r.getTitle(),r.getDescription(),r.getRequestType(),r.getChannel(),r.getPriority(),r.getApplicantName(),r.getApplicantContact(),r.getResponsibleUnitId(),r.getAssigneeId(),r.getDistrictId(),r.getNeighborhoodId(),r.getAddress(),writer.write(r.getGeometry()),r.getExternalReference(),r.getStatus(),r.getCreatedAt(),r.getUpdatedAt(),r.getVersion());}
}

