package tr.gov.kocaeli.sehir.document.application;
import io.minio.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;import tr.gov.kocaeli.sehir.audit.application.AuditService;import tr.gov.kocaeli.sehir.common.api.ApiException;import tr.gov.kocaeli.sehir.common.security.*;import tr.gov.kocaeli.sehir.request.application.RequestService;import java.io.*;import java.security.*;import java.time.*;import java.util.*;
@Service public class DocumentService{private static final long MAX=10*1024*1024;private static final Set<String>ALLOWED=Set.of("image/jpeg","image/png","application/pdf");private final MinioClient minio;private final String bucket;private final JdbcClient jdbc;private final CurrentUserService current;private final RequestService requests;private final AuditService audit;public DocumentService(MinioClient minio,@Value("${app.storage.bucket}")String bucket,JdbcClient jdbc,CurrentUserService current,RequestService requests,AuditService audit){this.minio=minio;this.bucket=bucket;this.jdbc=jdbc;this.current=current;this.requests=requests;this.audit=audit;}
 @Transactional public Map<String,Object>upload(String subjectType,UUID subjectId,String documentType,String description,MultipartFile file){authorize(subjectType,subjectId);if(file.isEmpty()||file.getSize()>MAX)throw new ApiException(HttpStatus.BAD_REQUEST,"FILE_SIZE","Dosya boş olamaz ve en fazla 10 MB olabilir");String mime=Objects.requireNonNullElse(file.getContentType(),"application/octet-stream");if(!ALLOWED.contains(mime))throw new ApiException(HttpStatus.BAD_REQUEST,"FILE_TYPE","Yalnızca JPEG, PNG veya PDF yüklenebilir");UUID id=UUID.randomUUID();String key=subjectType.toLowerCase(Locale.ROOT)+"/"+subjectId+"/"+id;try{ensureBucket();byte[]bytes=file.getBytes();String hash=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));minio.putObject(PutObjectArgs.builder().bucket(bucket).object(key).stream(new ByteArrayInputStream(bytes),bytes.length,-1).contentType(mime).build());jdbc.sql("insert into document_metadata(id,subject_type,subject_id,original_name,object_key,mime_type,size_bytes,sha256,document_type,description,uploaded_by)values(:id,:st,:si,:n,:k,:m,:z,:h,:dt,:d,:u)").param("id",id).param("st",subjectType).param("si",subjectId).param("n",Objects.requireNonNullElse(file.getOriginalFilename(),"dosya")).param("k",key).param("m",mime).param("z",bytes.length).param("h",hash).param("dt",documentType).param("d",description).param("u",current.require().id()).update();var result=metadata(id);audit.record("DOCUMENT_UPLOAD","DOCUMENT",id,null,result);return result;}catch(ApiException e){throw e;}catch(Exception e){throw new IllegalStateException("Dosya saklanamadı",e);}}
 public Download download(UUID id){var m=metadata(id);authorize((String)m.get("subjectType"),(UUID)m.get("subjectId"));try{var stream=minio.getObject(GetObjectArgs.builder().bucket(bucket).object((String)m.get("objectKey")).build());byte[]bytes=stream.readAllBytes();audit.record("FILE_ACCESS","DOCUMENT",id,null,Map.of("downloaded",true));return new Download(bytes,(String)m.get("mimeType"),(String)m.get("originalName"));}catch(Exception e){throw new IllegalStateException("Dosya okunamadı",e);}}
 private void authorize(String type,UUID id){if("REQUEST".equals(type))requests.get(id);else throw new ApiException(HttpStatus.BAD_REQUEST,"SUBJECT_TYPE","Bu sürümde REQUEST doküman bağlantısı desteklenir");}
 private void ensureBucket()throws Exception{if(!minio.bucketExists(BucketExistsArgs.builder().bucket(bucket).build()))minio.makeBucket(MakeBucketArgs.builder().bucket(bucket).build());}
 private Map<String,Object>metadata(UUID id){return jdbc.sql("select id,subject_type,subject_id,original_name,object_key,mime_type,size_bytes,sha256,document_type,description,uploaded_at,version_no from document_metadata where id=:id").param("id",id).query((rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getObject("id",UUID.class));m.put("subjectType",rs.getString("subject_type"));m.put("subjectId",rs.getObject("subject_id",UUID.class));m.put("originalName",rs.getString("original_name"));m.put("objectKey",rs.getString("object_key"));m.put("mimeType",rs.getString("mime_type"));m.put("sizeBytes",rs.getLong("size_bytes"));m.put("sha256",rs.getString("sha256"));m.put("documentType",rs.getString("document_type"));m.put("description",rs.getString("description"));m.put("uploadedAt",rs.getObject("uploaded_at"));m.put("versionNo",rs.getInt("version_no"));return m;}).optional().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"DOCUMENT_NOT_FOUND","Doküman bulunamadı"));}public record Download(byte[]bytes,String mimeType,String filename){}
}

