package tr.gov.kocaeli.sehir.approval.application;
import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import tr.gov.kocaeli.sehir.audit.application.AuditService;import tr.gov.kocaeli.sehir.common.api.ApiException;import tr.gov.kocaeli.sehir.common.security.*;import tr.gov.kocaeli.sehir.request.application.RequestService;import tr.gov.kocaeli.sehir.request.api.RequestDtos;import tr.gov.kocaeli.sehir.request.domain.RequestStatus;import java.util.*;
@Service public class ApprovalService{
 private final JdbcClient jdbc;private final CurrentUserService current;private final RequestService requests;private final AuditService audit;public ApprovalService(JdbcClient jdbc,CurrentUserService current,RequestService requests,AuditService audit){this.jdbc=jdbc;this.current=current;this.requests=requests;this.audit=audit;}
 @Transactional public Map<String,Object>submit(Submit c){var r=requests.get(c.requestId());if(r.status()!=RequestStatus.DECISION_PENDING)throw new ApiException(HttpStatus.CONFLICT,"REQUEST_NOT_READY","Talep karar/onay bekliyor durumunda olmalıdır");UUID id=UUID.randomUUID();jdbc.sql("insert into approval_instance(id,subject_type,subject_id,level,status,requested_by,current_approver_id) values(:id,'REQUEST',:s,1,'PENDING',:u,:a)").param("id",id).param("s",c.requestId()).param("u",current.require().id()).param("a",c.approverId()).update();notify(c.approverId(),"APPROVAL_REQUESTED","Onayınıza kayıt gönderildi",r.requestNo()+" numaralı talep onayınızı bekliyor","/requests");audit.record("APPROVAL_SUBMIT","APPROVAL",id,null,c);return get(id);}
 @Transactional public Map<String,Object>decide(UUID id,Decision c){var a=get(id);if(!"PENDING".equals(a.get("status")))throw new ApiException(HttpStatus.CONFLICT,"APPROVAL_COMPLETED","Onay kaydı daha önce sonuçlandırılmış");if(!Objects.equals(a.get("currentApproverId"),current.require().id())&&!current.require().isAdmin())throw new ApiException(HttpStatus.FORBIDDEN,"APPROVER_REQUIRED","Bu karar için onay yetkiniz yok");String next=switch(c.decision()){case"APPROVED"->"APPROVED";case"REJECTED"->"REJECTED";case"RETURNED_FOR_CORRECTION"->"RETURNED_FOR_CORRECTION";default->throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_DECISION","Geçersiz karar");};jdbc.sql("insert into approval_decision(id,approval_id,decision,decided_by,explanation,previous_status,next_status) values(:d,:a,:v,:u,:e,'PENDING',:n)").param("d",UUID.randomUUID()).param("a",id).param("v",c.decision()).param("u",current.require().id()).param("e",c.explanation()).param("n",next).update();jdbc.sql("update approval_instance set status=:s,completed_at=now() where id=:id").param("s",next).param("id",id).update();UUID requestId=(UUID)a.get("subjectId");if("APPROVED".equals(next)){if("PROJECT".equals(c.conversionType()))convertProject(requestId);else if("ACTIVITY".equals(c.conversionType()))convertActivity(requestId);else throw new ApiException(HttpStatus.BAD_REQUEST,"CONVERSION_REQUIRED","PROJECT veya ACTIVITY dönüşüm türü zorunludur");}else if("REJECTED".equals(next))requests.transition(requestId,new RequestDtos.Transition(RequestStatus.REJECTED,c.explanation()));else requests.transition(requestId,new RequestDtos.Transition(RequestStatus.FIELD_REVIEW,c.explanation()));audit.record(c.decision(),"APPROVAL",id,a,get(id));return get(id);}
 private void convertProject(UUID requestId){var r=requests.get(requestId);UUID id=UUID.randomUUID();String code=jdbc.sql("select 'PRJ-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('project_code_seq')::text,5,'0')").query(String.class).single();jdbc.sql("insert into project_candidate(id,project_code,name,project_type,description,responsible_unit_id,priority,geometry,status) select :id,:c,title,'INFRASTRUCTURE',description,responsible_unit_id,priority,geometry,'CANDIDATE' from city_request where id=:r").param("id",id).param("c",code).param("r",requestId).update();jdbc.sql("insert into project_request(project_id,request_id) values(:p,:r)").param("p",id).param("r",requestId).update();requests.transition(requestId,new RequestDtos.Transition(RequestStatus.CONVERTED_TO_PROJECT,"Onayla proje adayına dönüştürüldü"));}
 private void convertActivity(UUID requestId){UUID id=UUID.randomUUID();String no=jdbc.sql("select 'FAL-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('activity_no_seq')::text,5,'0')").query(String.class).single();jdbc.sql("insert into activity(id,activity_no,activity_type,title,description,request_id,responsible_unit_id,geometry,status) select :id,:n,'MAINTENANCE',title,description,id,responsible_unit_id,geometry,'NEW' from city_request where id=:r").param("id",id).param("n",no).param("r",requestId).update();requests.transition(requestId,new RequestDtos.Transition(RequestStatus.CONVERTED_TO_ACTIVITY,"Onayla faaliyete dönüştürüldü"));}
 private void notify(UUID user,String type,String title,String body,String link){jdbc.sql("insert into notification(id,user_id,type,title,body,link)values(:id,:u,:t,:h,:b,:l)").param("id",UUID.randomUUID()).param("u",user).param("t",type).param("h",title).param("b",body).param("l",link).update();}
 public Map<String,Object>get(UUID id){var result=jdbc.sql("select id,subject_type,subject_id,level,status,requested_by,current_approver_id,created_at,completed_at from approval_instance where id=:id").param("id",id).query((rs,n)->{var m=new LinkedHashMap<String,Object>();m.put("id",rs.getObject("id",UUID.class));m.put("subjectType",rs.getString("subject_type"));m.put("subjectId",rs.getObject("subject_id",UUID.class));m.put("level",rs.getInt("level"));m.put("status",rs.getString("status"));m.put("requestedBy",rs.getObject("requested_by",UUID.class));m.put("currentApproverId",rs.getObject("current_approver_id",UUID.class));m.put("createdAt",rs.getObject("created_at"));m.put("completedAt",rs.getObject("completed_at"));return m;}).optional().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"APPROVAL_NOT_FOUND","Onay kaydı bulunamadı"));if("REQUEST".equals(result.get("subjectType")))requests.get((UUID)result.get("subjectId"));return result;}
 public record Submit(UUID requestId,UUID approverId){}public record Decision(String decision,String explanation,String conversionType){}
}
